// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqShortUrlId struct {
	Id string `path:"id"`
}

type ReqUrl struct {
	Url string `json:"url"`
}

type RespShortUrl struct {
	ShortUrl string `json:"shortened"`
}
