// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqShortCode struct {
	ShortCode string `path:"shortcode"`
}

type ReqUrl struct {
	Url string `json:"url"`
}

type RespRedirect struct {
	Url string `json:"url"`
}

type RespShortUrl struct {
	ShortUrl string `json:"shortened"`
}
