CREATE DATABASE IF NOT EXISTS shorter_db DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
USE shorter_db;
DROP TABLE IF EXISTS shorter;
CREATE TABLE shorter (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    raw_url VARCHAR(512) NOT NULL UNIQUE,
    short_code VARCHAR(16) UNIQUE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;